### ISSUE TITLE
Proposal: subscribe command used with argument instead of context channel.

### ISSUE THREAD

**Issue by ThePugi** [RbxAPI/Docs-Bot#25] opened 2020-01-11 21:19 UTC
I'm proposing that instead of using the channel that the command was called from, it is instead passed with an argument to give the news role.

**Currently the command is very spam-like in library channels, and bumps them unnecessarily.**

Opinions would be appreciated!

**Comment by sbhadr** [comment] 2020-01-11 21:34
``?subscribe`` is designed to be automatic and fluid to allow for adaptation and discourage the concept of static coding. This is done for a variety of reasons, in particular, would be dynamic loading. 
Context: https://github.com/RbxAPI/Docs-Bot/blob/rewrite/main.py#L154

The method itself checks to see if the news role is valid in the server by matching the channel name (from which the command was invoked it) with the keyword ``news``. The full channel name is not used and is broken up with ``_`` being the division operator. For instance, if you had a channel in your server called, ``python_pyblox``, the ``python_`` of that phrase would be ignored and instead use ``pyblox``. From there, if the role ``pyblox news`` exists in the server, the role is added to the user. 
https://github.com/RbxAPI/Docs-Bot/blob/rewrite/main.py#L163
https://github.com/RbxAPI/Docs-Bot/blob/rewrite/main.py#L164
https://github.com/RbxAPI/Docs-Bot/blob/rewrite/main.py#L172
https://github.com/RbxAPI/Docs-Bot/blob/rewrite/main.py#L173

> Currently the command is very spam-like in library channels, and bumps them unnecessarily.

While a byproduct to this functionality causes the channel to be bumped, it's more of an indicator to library developers that people are viewing their progress and want to receive updates when progress is pushed, fixed or dismissed.

**Comment by Pythonic-Rainbow** [comment] 2020-01-11 22:55
Maybe we can implement both at the same time?

**Comment by sbhadr** [comment] 2020-01-12 18:15
I prefer not to.

**Comment by ThePugi** [comment] 2020-01-12 18:31
> `?subscribe` is designed to be automatic and fluid to allow for adaptation and discourage the concept of static coding. This is done for a variety of reasons, in particular, would be dynamic loading.

I can get behind no static code. I think the command could be adapted to keep its current code method by providing an argument with the channel link (eg `?subscribe #this_is_a_channel`) and getting the name from the provided ID.

Mainly, I think this change would benefit those who keep library channels unmuted for the reason of knowing when someone asks for help, and generally just keep this command centralized to a bot-cmds channel.

**Comment by sbhadr** [comment] 2020-01-13 23:45
First and foremost, sorry for the late reply. I've been busy. 

Secondly, after some thought perhaps this could work. ``?subscribe #this_is_a_channel`` . 
I'll work on an implementation of this directly after this issue is closed ( https://github.com/RbxAPI/Docs-Bot/issues/24 ). 

For the time being, I'll accept this as a proposal. Closing.

**Closed as completed by sbhadr** 2020-01-13 23:45 UTC
Labels: proposal, accepted

**Comment by Pythonic-Rainbow** [comment] 2020-01-13 23:57
Might as well do it inside #26

**Comment by sbhadr** [comment] 2020-01-14 01:51
This proposal has been added via https://github.com/RbxAPI/Docs-Bot/pull/26 . 

The new optional parameter is channel. ``?subscribe <channel>``. As of now, this channel will only be accepted as a parameter if it's invoked in the "#bot_commands" channel. Otherwise, ``?subscribe`` will still work as intended before. 

Locking issue since the proposal merged with the ``rewrite`` branch.
